routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/', 'WebController@index')->name('index');
Route::get('/post/{id}', 'WebController@post')->name('post')->where('id', '\d+');
Route::get('/author/{id}', 'WebController@author')->name('author')->where('id', '\d+');
Route::get('/catalog/{id}', 'WebController@catalog')->name('catalog')->where('id', '\d+');

Route::prefix('/store')
    ->name('store.')
    ->group( function (){
        Route::get('/', 'StoreController@index')->name('index');
        Route::get('/good/{id}', 'StoreController@good')->name('good')->where('id', '\d+');
        //Route::get('/author/{id}', 'StoreController@author')->name('author');
        Route::get('/catalog/{id}', 'StoreController@catalog')->name('catalog')->where('id', '\d+');
});

Route::prefix('/member')
    ->name('member.')
    ->group(function (){
        Route::get('/', 'MemberController@index')->name('index');
        Route::get('/login', 'MemberController@login')->name('login');
        Route::post('/loginc', 'MemberController@loginc')->name('loginc');
        Route::get('/logout', 'MemberController@logout')->name('logout');
    });

Route::namespace('Admin')
    ->prefix('/admin')
    ->middleware(['auth', 'can:view-admin'])
    ->group(function (){
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::post('/upload', 'AdminController@uploadImg')->name('admin.upload');
    Route::resource('/posts', 'PostsController');
    Route::resource('/catalogs', 'CatalogsController');
    Route::resource('/goods', 'GoodsController');
    Route::resource('/users', 'UsersController')->middleware('can:manage-users');
});

//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'level'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function goods()
    {
        return $this->hasMany(Good::class);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.index',[
            'rows' => User::paginate(5)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        User::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
            'level' => $request->input('level')
        ]);

        return response()->redirectToRoute('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('users.show',[
            'row' => User::findOrFail($id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('users.edit',[
            'row' => User::findOrFail($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = [
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'level' => $request->input('level')
        ];

        if($request->filled('password')){
            array_merge($data,[
                'password' => Hash::make($request->input('password'))
            ]);
        }

        User::findOrFail($id)->
            update($data);

        return response()->redirectToRoute('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);

        return response()->redirectToRoute('users.index');
    }
}

resources/views/users/create.blade.php
@extends('tpl.main-admin')

@section('title', '新增帳號')

@section('subtitle', '來新增一個帳號吧!')

@section('customHead')
    <style>
        header.masthead {
            background-image: url({{ asset('img/home-bg.jpg') }});
        }
    </style>
@endsection

@section('content')
    <form action="{{ route('users.store') }}" method="post">
        @csrf
        <table class="table table-bordered">
            <thead class="thead-dark text-center">
            <tr>
                <th colspan="2">新增帳號</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>名稱:</td>
                    <td><input type="text" name="name" class="form-control" required></td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td><input type="email" name="email" pattern="^(.+)@(.+)\.[a-z]{2,}$" class="form-control" required></td>
                </tr>
                <tr>
                    <td>密碼:</td>
                    <td><input type="password" name="password" class="form-control" required></td>
                </tr>
                <tr>
                    <td>等級</td>
                    <td>
                        <select name="level" class="form-control" required>
                            <option value="a">管理員</option>
                            <option value="e">編輯</option>
                            <option value="u">會員</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"><button type="submit" class="btn btn-primary">新增</button></td>
                </tr>
            </tbody>
        </table>
    </form>
@endsection

@section('customJs')
@endsection

resources/views/users/edit.blade.php
@extends('tpl.main-admin')

@section('title', '編輯帳號')

@section('subtitle', '來編輯一個帳號吧!')

@section('customHead')
    <style>
        header.masthead {
            background-image: url({{ asset('img/home-bg.jpg') }});
        }
    </style>
@endsection

@section('content')
    <form action="{{ route('users.update', ['id' => $row->id]) }}" method="post">
        @csrf
        @method('patch')
        <table class="table table-bordered">
            <thead class="thead-dark text-center">
            <tr>
                <th colspan="2">編輯帳號</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>NO.</td>
                    <td>
                        <input type="text" class="form-control" value="{{ $row->id }}" title="不能改" readonly="readonly">
                    </td>
                </tr>
                <tr>
                    <td>名稱:</td>
                    <td><input type="text" name="name" class="form-control" value="{{ $row->name }}" required></td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td><input type="email" name="email" pattern="^(.+)@(.+)\.[a-z]{2,}$" class="form-control" value="{{ $row->email }}" required></td>
                </tr>
                <tr>
                    <td>密碼:</td>
                    <td><input type="password" name="password" class="form-control"></td>
                </tr>
                <tr>
                    <td>等級</td>
                    <td>
                        @if($row->level == "root")
                            <input type="hidden" name="level" value="root">
                            <input type="text" value="最高管理員" class="form-control" title="不能改" readonly>
                        @else
                        <select name="level" class="form-control" required>
                            <option value="a" @if($row->level == "a") selected @endif>管理員</option>
                            <option value="e" @if($row->level == "e") selected @endif>編輯</option>
                            <option value="u" @if($row->level == "u") selected @endif>會員</option>
                        </select>
                        @endif
                    </td>
                </tr>
                <tr>
                    <td>發表於:</td>
                    <td><input type="text" class="form-control" value="{{ $row->created_at }}" title="不能改" readonly="readonly"></td>
                </tr>
                <tr>
                    <td>更新於:</td>
                    <td><input type="text" class="form-control" value="{{ $row->updated_at }}" title="不能改" readonly="readonly"></td>
                </tr>
                <tr>
                    <td colspan="2"><button type="submit" class="btn btn-primary">編輯</button></td>
                </tr>
            </tbody>
        </table>
    </form>
@endsection

@section('customJs')
@endsection

resources/views/users/index.blade.php
@extends('tpl.main-admin')

@section('title', '帳號列表')

@section('subtitle', '這是真正的帳號列表')

@section('customHead')
    <style>
        header.masthead {
            background-image: url({{ asset('img/home-bg.jpg') }});
        }
    </style>
    <script>
        function deleteCheck(name) {
            return confirm('您確定要刪除帳號[' + name + ']嗎?');
        }
    </script>
@endsection

@section('content')
    <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
            <th>No.</th>
            <th>名稱</th>
            <th>Email</th>
            <th>權限</th>
            <th>新增於</th>
            <th>動作</th>
        </tr>
        </thead>
        <tbody>
        @foreach($rows as $row)
            <tr>
                <td>{{ $row->id }}</td>
                <td>{{ $row->name }}</td>
                <td>{{ $row->email }}</td>
                <td>
                    @switch($row->level)
                        @case('root')
                        <span class="badge badge-dark">最高管理者</span>
                        @break
                        @case('a')
                        <span class="badge badge-success">管理者</span>
                        @break
                        @case('e')
                        <span class="badge badge-warning">編輯</span>
                        @break
                        @case('u')
                        <span class="badge badge-info">會員</span>
                    @endswitch
                </td>
                <td>{{ $row->created_at }}</td>
                <td>
                    <a href="{{ route('users.show', ['id'=>$row->id]) }}" class="btn btn-info">詳細</a>
                    <a href="{{ route('users.edit', ['id'=>$row->id]) }}" class="btn btn-warning">編輯</a>
                    @if($row->level == "root")
                        <button type="button" class="btn btn-danger disabled" disabled title="不能刪">刪除</button>
                    @else
                    <form action="{{ route('users.destroy', ['id'=>$row->id]) }}" method="post" style="display: inline;">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger" onclick="return deleteCheck('{{ $row->name }}')">刪除</button>
                    </form>
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $rows->links() }}
@endsection

@section('customJs')
@endsection

resources/views/users/show.blade.php
@extends('tpl.main-admin')

@section('title', '顯示帳號')

@section('subtitle', '顯示帳號')

@section('customHead')
    <style>
        header.masthead {
            background-image: url({{ asset('img/home-bg.jpg') }});
        }
    </style>
@endsection

@section('content')
    <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
            <th colspan="2">顯示帳號</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>No.</td>
            <td>{{ $row->id }}</td>
        </tr>
        <tr>
            <td>名稱</td>
            <td>{{ $row->name }}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{ $row->email }}</td>
        </tr>
        <tr>
            <td>Email驗證於</td>
            <td>{{ $row->email_verified_at }}</td>
        </tr>
        <tr>
            <td>等級</td>
            <td>
                @switch($row->level)
                    @case('root')
                    <span class="badge badge-dark">最高管理者</span>
                    @break
                    @case('a')
                    <span class="badge badge-success">管理者</span>
                    @break
                    @case('e')
                    <span class="badge badge-warning">編輯</span>
                    @break
                    @case('u')
                    <span class="badge badge-info">會員</span>
                @endswitch
            </td>
        </tr>
        <tr>
            <td>新增於</td>
            <td>{{ $row->created_at }}</td>
        </tr>
        <tr>
            <td>更新於</td>
            <td>{{ $row->updated_at }}</td>
        </tr>
        </tbody>
    </table>
@endsection

@section('customJs')
@endsection