routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/', 'WebController@index')->name('index');
Route::get('/post/{id}', 'WebController@post')->name('post')->where('id', '\d+');
Route::get('/author/{id}', 'WebController@author')->name('author')->where('id', '\d+');
Route::get('/catalog/{id}', 'WebController@catalog')->name('catalog')->where('id', '\d+');

Route::prefix('/store')
    ->name('store.')
    ->group( function (){
        Route::get('/', 'StoreController@index')->name('index');
        Route::get('/good/{id}', 'StoreController@good')->name('good')->where('id', '\d+');
        //Route::get('/author/{id}', 'StoreController@author')->name('author');
        Route::get('/catalog/{id}', 'StoreController@catalog')->name('catalog')->where('id', '\d+');
});

Route::prefix('/member')
    ->name('member.')
    ->group(function (){
        Route::get('/', 'MemberController@index')->name('index');
        Route::get('/login', 'MemberController@login')->name('login');
        Route::post('/loginc', 'MemberController@loginc')->name('loginc');
        Route::get('/logout', 'MemberController@logout')->name('logout');
    });

Route::namespace('Admin')
    ->prefix('/admin')
    ->middleware(['auth', 'can:view-admin'])
    ->group(function (){
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::post('/upload', 'AdminController@uploadImg')->name('admin.upload');
    Route::resource('/posts', 'PostsController');
    Route::resource('/catalogs', 'CatalogsController');
    Route::resource('/goods', 'GoodsController');
    Route::resource('/users', 'UsersController')->middleware('can:manage-users');
});

//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = ['id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function catalogs()
    {
        return $this->belongsToMany(Catalog::class);
    }
}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Catalog;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Post;
use Illuminate\Support\Facades\Cache;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('posts.index', [
            'rows' => Post::with('user:id,name')
                        ->paginate(5)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Post::class);

        return view('posts.create', [
            'catalogs' => Catalog::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //新增文章
        $post = Post::create([
            'user_id' => $request->input('user_id'),
            'title' => $request->input('title'),
            'content' => $request->input('content')
        ]);
        //更新多對多關聯
        $post->catalogs()->attach($request->input('catalogs'));

        //清除緩存
        Cache::flush();

        return response()->redirectToRoute('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->authorize('view', new Post());

        return view('posts.show', [
            'row' => Post::findOrFail($id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $row = Post::findOrFail($id);

        $this->authorize('update', $row);//檢查帳號是否有更新的權限

        $selectCatalogs = $row->catalogs
                            ->pluck('id')
                            ->all();//回傳分類的陣列

        return view('posts.edit',[
            'row' => $row,
            'selectCatalogs' => $selectCatalogs,
            'catalogs' => Catalog::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::findOrFail($id);
        $post->update([
            'title' => $request->input('title'),
            'content' => $request->input('content')
        ]);

        //更新關聯
        $post->catalogs()->sync($request->input('catalogs'));

        //清除緩存
        Cache::flush();

        return response()->redirectToRoute('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->authorize('delete', Post::findOrFail($id));//檢查帳號是否有刪除的權限

        Post::destroy($id);

        //清除緩存
        Cache::flush();

        return response()->redirectToRoute('posts.index');
    }
}

resources/views/posts/create.blade.php
@extends('tpl.main-admin')

@section('title', '發表文章')

@section('subtitle', '來發表一篇文章吧!')

@section('customHead')
    <style>
        header.masthead {
            background-image: url({{ asset('img/about-bg.jpg') }});
        }
    </style>
@endsection

@section('content')
    <form action="{{ route('posts.store') }}" method="post">
        @csrf
        <table class="table table-bordered">
            <thead class="thead-dark text-center">
            <tr>
                <th colspan="2">發表文章</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>發表會員:</td>
                    <td>
                        <input type="hidden" name="user_id" pattern="\d+" value="{{ \Illuminate\Support\Facades\Auth::id() }}" required>
                        <input type="text" class="form-control" value="{{ \Illuminate\Support\Facades\Auth::user()->name }}" readonly="readonly">
                    </td>
                </tr>
                <tr>
                    <td>標題:</td>
                    <td><input type="text" name="title" maxlength="50" class="form-control" required></td>
                </tr>
                <tr>
                    <td>內容:</td>
                    <td><textarea name="content" class="form-control" rows="3" id="editor"></textarea></td>
                </tr>
                <tr>
                    <td>分類</td>
                    <td>
                        <select name="catalogs[]" multiple required class="form-control">
                            @foreach($catalogs as $catalog)
                                <option value="{{ $catalog->id }}">{{ $catalog->name }}</option>
                            @endforeach
                        </select>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"><button type="submit" class="btn btn-primary">發表</button></td>
                </tr>
            </tbody>
        </table>
    </form>
@endsection

@section('customJs')
    @include('tpl.editor',['editorId'=>'#editor'])
@endsection

resources/views/posts/edit.blade.php
@extends('tpl.main-admin')

@section('title', '編輯文章')

@section('subtitle', '來編輯一篇文章吧!')

@section('customHead')
    <style>
        header.masthead {
            background-image: url({{ asset('img/about-bg.jpg') }});
        }
    </style>
@endsection

@section('content')
    <form action="{{ route('posts.update', ['id' => $row->id]) }}" method="post">
        @csrf
        @method('patch')
        <table class="table table-bordered">
            <thead class="thead-dark text-center">
            <tr>
                <th colspan="2">編輯文章</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>NO.</td>
                    <td>
                        <input type="text" class="form-control" value="{{ $row->id }}" title="不能改" readonly="readonly">
                    </td>
                </tr>
                <tr>
                    <td>發表會員:</td>
                    <td>
                        <input type="text" class="form-control" value="{{ $row->user->name }}" title="不能改" readonly="readonly">
                    </td>
                </tr>
                <tr>
                    <td>標題:</td>
                    <td><input type="text" name="title" maxlength="50" class="form-control" value="{{ $row->title }}" required></td>
                </tr>
                <tr>
                    <td>內容:</td>
                    <td><textarea name="content" class="form-control" rows="3"  id="editor" required>{{ $row->content }}</textarea></td>
                </tr>
                <tr>
                    <td>分類</td>
                    <td>
                        <select name="catalogs[]" multiple required class="form-control">
                            @foreach($catalogs as $catalog)
                                <option value="{{ $catalog->id }}" @if(in_array($catalog->id, $selectCatalogs)) selected @endif>{{ $catalog->name }}</option>
                            @endforeach
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>發表於:</td>
                    <td><input type="text" maxlength="50" class="form-control" value="{{ $row->created_at }}" title="不能改" readonly="readonly"></td>
                </tr>
                <tr>
                    <td>更新於:</td>
                    <td><input type="text" maxlength="50" class="form-control" value="{{ $row->updated_at }}" title="不能改" readonly="readonly"></td>
                </tr>
                <tr>
                    <td colspan="2"><button type="submit" class="btn btn-primary">編輯</button></td>
                </tr>
            </tbody>
        </table>
    </form>
@endsection

@section('customJs')
    @include('tpl.editor',['editorId'=>'#editor'])
@endsection

resources/views/posts/index.blade.php
@extends('tpl.main-admin')

@section('title', '文章列表')

@section('subtitle', '這是真正的文章列表')

@section('customHead')
    <style>
        header.masthead {
            background-image: url({{ asset('img/post-bg.jpg') }});
        }
    </style>
    <script>
        function deleteCheck(name) {
            return confirm('您確定要刪除文章[' + name + ']嗎?');
        }
    </script>
@endsection

@section('content')
    <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
            <th>No.</th>
            <th>帳號</th>
            <th>標題</th>
            <th>發表於</th>
            <th>動作</th>
        </tr>
        </thead>
        <tbody>
        @foreach($rows as $row)
            <tr>
                <td>{{ $row->id }}</td>
                <td>{{ $row->user->name }}</td>
                <td>{{ $row->title }}</td>
                <td>{{ $row->created_at }}</td>
                <td>
                    <a href="{{ route('posts.show', ['id'=>$row->id]) }}" class="btn btn-info">詳細</a>
                    <a href="{{ route('posts.edit', ['id'=>$row->id]) }}" class="btn btn-warning">編輯</a>
                    <form action="{{ route('posts.destroy', ['id'=>$row->id]) }}" method="post" style="display: inline;">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger" onclick="return deleteCheck('{{ $row->title }}')">刪除</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $rows->links() }}
@endsection

@section('customJs')

@endsection

resources/views/posts/show.blade.php
@extends('tpl.main-admin')

@section('title', '顯示文章')

@section('subtitle', '顯示文章')

@section('customHead')
    <style>
        header.masthead {
            background-image: url({{ asset('img/post-bg.jpg') }});
        }
    </style>
@endsection

@section('content')
    <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
            <th colspan="2">顯示文章</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>編號</td>
            <td>{{ $row->id }}</td>
        </tr>
        <tr>
            <td>使用者</td>
            <td>{{ $row->user->name }}</td>
        </tr>
        <tr>
            <td>標題</td>
            <td>{{ $row->title }}</td>
        </tr>
        <tr>
            <td>內容</td>
            <td>{!!  $row->content !!}</td>
        </tr>
        <tr>
            <td>發表於</td>
            <td>{{ $row->created_at }}</td>
        </tr>
        <tr>
            <td>更新於</td>
            <td>{{ $row->updated_at }}</td>
        </tr>
        <tr>
            <td colspan="2">
                @foreach($row->catalogs as $catalog)
                    <span class="badge badge-info word-0">
                        {{ $catalog->name  }}
                    </span>
                @endforeach
            </td>
        </tr>
        </tbody>
    </table>
@endsection

@section('customJs')
@endsection