routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/', 'WebController@index')->name('index');
Route::get('/post/{id}', 'WebController@post')->name('post')->where('id', '\d+');
Route::get('/author/{id}', 'WebController@author')->name('author')->where('id', '\d+');
Route::get('/catalog/{id}', 'WebController@catalog')->name('catalog')->where('id', '\d+');

Route::prefix('/store')
    ->name('store.')
    ->group( function (){
        Route::get('/', 'StoreController@index')->name('index');
        Route::get('/good/{id}', 'StoreController@good')->name('good')->where('id', '\d+');
        //Route::get('/author/{id}', 'StoreController@author')->name('author');
        Route::get('/catalog/{id}', 'StoreController@catalog')->name('catalog')->where('id', '\d+');
});

Route::prefix('/member')
    ->name('member.')
    ->group(function (){
        Route::get('/', 'MemberController@index')->name('index');
        Route::get('/login', 'MemberController@login')->name('login');
        Route::post('/loginc', 'MemberController@loginc')->name('loginc');
        Route::get('/logout', 'MemberController@logout')->name('logout');
    });

Route::namespace('Admin')
    ->prefix('/admin')
    ->middleware(['auth', 'can:view-admin'])
    ->group(function (){
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::post('/upload', 'AdminController@uploadImg')->name('admin.upload');
    Route::resource('/posts', 'PostsController');
    Route::resource('/catalogs', 'CatalogsController');
    Route::resource('/goods', 'GoodsController');
    Route::resource('/users', 'UsersController')->middleware('can:manage-users');
});

//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

resources/views/tpl/customJs.blade.php
<!-- Bootstrap core JavaScript -->
<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>

<!-- Custom scripts for this template -->
<script src="{{ asset('js/clean-blog.min.js') }}"></script>

resources/views/tpl/editor.blade.php
<script src="{{ asset('js/ckeditor/ckeditor.js') }}"></script>
<script>
    ClassicEditor
        .create( document.querySelector( '{{ $editorId }}' ), {
            ckfinder: {
                uploadUrl: '{{ route('admin.upload') }}',
                options:{
                    resourceType: 'Images'
                },
                openerMethod: 'modal'
            },
            image: {
                toolbar: [ 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight', '|', 'imageTextAlternative' ],
                styles: [
                    'full',
                    'alignLeft',
                    'alignRight'
                ]
            }
        })
        /*.then( editor => {
            console.log( editor )
        })*/
        .catch( error => {
            console.error( error );
        });
</script>

resources/views/tpl/footer.blade.php
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://www.facebook.com/weitai168.com.tw">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; 韋泰茶具茶葉商行 2019</p>
            </div>
        </div>
    </div>
</footer>

resources/views/tpl/head.blade.php
<!-- Bootstrap core CSS -->
<link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">

<!-- Custom fonts for this template -->
<link href="{{ asset('css/fontawesome/css/all.min.css') }}" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
      type='text/css'>
<link
    href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
    rel='stylesheet' type='text/css'>

<!-- Custom styles for this template -->
<link href="{{ asset('css/clean-blog.min.css') }}" rel="stylesheet">

<!-- Custom css-->
<link rel="stylesheet" href="{{ asset('css/custom.min.css') }}">

resources/views/tpl/main-admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('title')</title>

    @include('tpl.head')
    {{--自訂義網頁標頭--}}
    @yield('customHead')

</head>

<body>

<!-- Navigation -->
@include('tpl.nav-admin')

<!-- Page Header -->
<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>@yield('title')</h1>
                    <span class="subheading">@yield('subtitle')</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            @section('content')
            @show
        </div>
    </div>
</div>

<hr>

<!-- Footer -->
@include('tpl.footer')

@include('tpl.customJs')
{{--自訂義Javascript檔案--}}
@yield('customJs')

</body>

</html>

resources/views/tpl/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('title')</title>

    @include('tpl.head')
    {{--自訂義網頁標頭--}}
    @yield('customHead')

</head>

<body>

<!-- Navigation -->
@include('tpl.nav')

<!-- Page Header -->
<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>@yield('title')</h1>
                    <span class="subheading">@yield('subtitle')</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            @section('content')
            @show
        </div>
    </div>
</div>

<hr>

<!-- Footer -->
@include('tpl.footer')

@include('tpl.customJs')
{{--自訂義Javascript檔案--}}
@yield('customJs')

</body>

</html>

resources/views/tpl/nav-admin.blade.php
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{{ route('index') }}">韋泰茶具茶葉商行</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('admin.index') }}">控制台</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="postsMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        帳號管理
                    </a>
                    <div class="dropdown-menu" aria-labelledby="postsMenu">
                        <a class="dropdown-item" href="{{ route('users.index') }}">帳號列表</a>
                        <a class="dropdown-item" href="{{ route('users.create') }}">新增帳號</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="postsMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        文章
                    </a>
                    <div class="dropdown-menu" aria-labelledby="postsMenu">
                        <a class="dropdown-item" href="{{ route('posts.index') }}">文章列表</a>
                        <a class="dropdown-item" href="{{ route('posts.create') }}">發表文章</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="catalogsMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        分類
                    </a>
                    <div class="dropdown-menu" aria-labelledby="catalogsMenu">
                        <a class="dropdown-item" href="{{ route('catalogs.index') }}">分類列表</a>
                        <a class="dropdown-item" href="{{ route('catalogs.create') }}">新增分類</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="catalogsMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        商品
                    </a>
                    <div class="dropdown-menu" aria-labelledby="catalogsMenu">
                        <a class="dropdown-item" href="{{ route('goods.index') }}">商品列表</a>
                        <a class="dropdown-item" href="{{ route('goods.create') }}">新增商品</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="frontMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        前台
                    </a>
                    <div class="dropdown-menu" aria-labelledby="frontMenu">
                        <a class="dropdown-item" href="{{ route('member.index') }}">前往前台</a>
                        <a class="dropdown-item" href="{{ route('member.logout') }}">登出</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/tpl/nav.blade.php
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{{ route('index') }}">韋泰茶具茶葉商行</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('index') }}">首頁</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('store.index') }}">商店</a>
                </li>
                @auth
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="frontMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            前台列表
                        </a>
                        <div class="dropdown-menu" aria-labelledby="frontMenu">
                            <a class="dropdown-item" href="{{ route('member.index') }}">前往前台</a>
                            <a class="dropdown-item" href="{{ route('member.logout') }}">登出</a>
                        </div>
                    </li>
                    @can('view-admin')
                        <li class="nav-item">
                            <a href="{{ route('admin.index') }}" class="nav-link">後台</a>
                        </li>
                    @endcan
                @else
                    <li class="nav-item">
                        <a href="{{ route('member.login') }}" class="nav-link">登入</a>
                    </li>
                @endauth
            </ul>
        </div>
    </div>
</nav>