routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/', 'WebController@index')->name('index');
Route::get('/post/{id}', 'WebController@post')->name('post')->where('id', '\d+');
Route::get('/author/{id}', 'WebController@author')->name('author')->where('id', '\d+');
Route::get('/catalog/{id}', 'WebController@catalog')->name('catalog')->where('id', '\d+');

Route::prefix('/store')
    ->name('store.')
    ->group( function (){
        Route::get('/', 'StoreController@index')->name('index');
        Route::get('/good/{id}', 'StoreController@good')->name('good')->where('id', '\d+');
        //Route::get('/author/{id}', 'StoreController@author')->name('author');
        Route::get('/catalog/{id}', 'StoreController@catalog')->name('catalog')->where('id', '\d+');
});

Route::prefix('/member')
    ->name('member.')
    ->group(function (){
        Route::get('/', 'MemberController@index')->name('index');
        Route::get('/login', 'MemberController@login')->name('login');
        Route::post('/loginc', 'MemberController@loginc')->name('loginc');
        Route::get('/logout', 'MemberController@logout')->name('logout');
    });

Route::namespace('Admin')
    ->prefix('/admin')
    ->middleware(['auth', 'can:view-admin'])
    ->group(function (){
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::post('/upload', 'AdminController@uploadImg')->name('admin.upload');
    Route::resource('/posts', 'PostsController');
    Route::resource('/catalogs', 'CatalogsController');
    Route::resource('/goods', 'GoodsController');
    Route::resource('/users', 'UsersController')->middleware('can:manage-users');
});

//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Catalog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Catalog extends Model
{
    protected $guarded = ['id'];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }

    public function goods()
    {
        return $this->belongsToMany(Good::class);
    }
}

app/Http/Controllers/Admin/CatalogsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Catalog;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cache;

class CatalogsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('catalogs.index',[
            'rows' => Catalog::paginate(5)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('catalogs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $catalog = Catalog::create([
            'name' => $request->input('name')
        ]);

        //清除緩存
        Cache::flush();

        return response()->redirectToRoute('catalogs.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $row = Catalog::findOrFail($id);

        return view('catalogs.show',[
            'row' => $row,
            'posts' => $row->posts()
                            ->count('id'),
            'goods' => $row->goods()
                            ->count('id')
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('catalogs.edit',[
            'row' => Catalog::findOrFail($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Catalog::findOrFail($id)
                ->update([
                    'name' => $request->input('name')
                ]);

        //清除緩存
        Cache::flush();

        return response()->redirectToRoute('catalogs.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Catalog::destroy($id);

        //清除緩存
        Cache::flush();

        return response()->redirectToRoute('catalogs.index');
    }
}

resources/views/catalogs/create.blade.php
@extends('tpl.main-admin')

@section('title', '新增分類')

@section('subtitle', '來新增一個分類吧!')

@section('customHead')
    <style>
        header.masthead {
            background-image: url({{ asset('img/contact-bg.jpg') }});
        }
    </style>
@endsection

@section('content')
    <form action="{{ route('catalogs.store') }}" method="post">
        @csrf
        <table class="table table-bordered">
            <thead class="thead-dark text-center">
            <tr>
                <th colspan="2">新增分類</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>名稱:</td>
                    <td><input type="text" name="name" maxlength="20" class="form-control" required></td>
                </tr>
                <tr>
                    <td colspan="2"><button type="submit" class="btn btn-primary">新增</button></td>
                </tr>
            </tbody>
        </table>
    </form>
@endsection

@section('customJs')
@endsection

resources/views/catalogs/edit.blade.php
@extends('tpl.main-admin')

@section('title', '編輯分類')

@section('subtitle', '來編輯一個分類吧!')

@section('customHead')
    <style>
        header.masthead {
            background-image: url({{ asset('img/contact-bg.jpg') }});
        }
    </style>
@endsection

@section('content')
    <form action="{{ route('catalogs.update', ['id' => $row->id]) }}" method="post">
        @csrf
        @method('patch')
        <table class="table table-bordered">
            <thead class="thead-dark text-center">
            <tr>
                <th colspan="2">編輯分類</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>NO.</td>
                    <td>
                        <input type="text" class="form-control" value="{{ $row->id }}" title="不能改" readonly="readonly">
                    </td>
                </tr>
                <tr>
                    <td>名稱:</td>
                    <td><input type="text" name="name" maxlength="20" class="form-control" value="{{ $row->name }}" required></td>
                </tr>
                <tr>
                    <td>發表於:</td>
                    <td><input type="text" class="form-control" value="{{ $row->created_at }}" title="不能改" readonly="readonly"></td>
                </tr>
                <tr>
                    <td>更新於:</td>
                    <td><input type="text" class="form-control" value="{{ $row->updated_at }}" title="不能改" readonly="readonly"></td>
                </tr>
                <tr>
                    <td colspan="2"><button type="submit" class="btn btn-primary">編輯</button></td>
                </tr>
            </tbody>
        </table>
    </form>
@endsection

@section('customJs')
@endsection

resources/views/catalogs/index.blade.php
@extends('tpl.main-admin')

@section('title', '分類列表')

@section('subtitle', '這是真正的分類列表')

@section('customHead')
    <style>
        header.masthead {
            background-image: url({{ asset('img/contact-bg.jpg') }});
        }
    </style>
    <script>
        function deleteCheck(name) {
            return confirm('您確定要刪除分類[' + name + ']嗎?');
        }
    </script>
@endsection

@section('content')
    <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
            <th>No.</th>
            <th>名稱</th>
            <th>新增於</th>
            <th>動作</th>
        </tr>
        </thead>
        <tbody>
        @foreach($rows as $row)
            <tr>
                <td>{{ $row->id }}</td>
                <td>{{ $row->name }}</td>
                <td>{{ $row->created_at }}</td>
                <td>
                    <a href="{{ route('catalogs.show', ['id'=>$row->id]) }}" class="btn btn-info">詳細</a>
                    <a href="{{ route('catalogs.edit', ['id'=>$row->id]) }}" class="btn btn-warning">編輯</a>
                    <form action="{{ route('catalogs.destroy', ['id'=>$row->id]) }}" method="post" style="display: inline;">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger" onclick="return deleteCheck('{{ $row->name }}')">刪除</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $rows->links() }}
@endsection

@section('customJs')
@endsection

resources/views/catalogs/show.blade.php
@extends('tpl.main-admin')

@section('title', '顯示分類')

@section('subtitle', '顯示分類')

@section('customHead')
    <style>
        header.masthead {
            background-image: url({{ asset('img/contact-bg.jpg') }});
        }
    </style>
@endsection

@section('content')
    <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
            <th colspan="2">顯示分類</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>No.</td>
            <td>{{ $row->id }}</td>
        </tr>
        <tr>
            <td>名稱</td>
            <td>{{ $row->name }}</td>
        </tr>
        <tr>
            <td>新增於</td>
            <td>{{ $row->created_at }}</td>
        </tr>
        <tr>
            <td>更新於</td>
            <td>{{ $row->updated_at }}</td>
        </tr>
        <tr>
            <td>文章量</td>
            <td>{{ $posts }}個</td>
        </tr>
        <tr>
            <td>商品量</td>
            <td>{{ $goods }}個</td>
        </tr>
        </tbody>
    </table>
@endsection

@section('customJs')
@endsection